version: '3.5'



services:


  redis:
    image: "redis:alpine"
    command: redis-server --requirepass changeit
    ports:
        - "7777:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
    #   - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master
  


  urlshortener.docker:
    image: ${DOCKER_REGISTRY-}urlshortner
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:443;http://+:80
     - ASPNETCORE_HTTPS_PORT=5001
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ClientApp/https/mycertificatename.pfx
     - ASPNETCORE_Kestrel__Certificates__Default__Password=mycertificatepassword
     
    build:
        context: .
        dockerfile: src/WebApp/Runtime.URLShortener/Docker/Dockerfile
    ports:
     - "5000:80"
     - "5001:443"

    depends_on:
        - redis
   
  
    


